networks:
  transcendence:
    driver: bridge

services:
  db:
    image: postgres:17.2-alpine
    hostname: db
    restart: always
    environment:
      POSTGRES_DB: testDb
      POSTGRES_USER: someUser
      POSTGRES_PASSWORD: somePassword
    networks:
      - transcendence

  user_service:
    image: "user_service"
    hostname: user_service
    build:
      context: .
      dockerfile: user_service/Dockerfile
    ports:
      - "8080:8080"
    networks:
      - transcendence
    depends_on:
      - db